### ISSUE TITLE
Wrong Name and Logo

### ISSUE THREAD

**Issue by Meligy** [egyptian-geeks/EgyptianGeeksArchive#14]
This is using the name of logo of "EgyGeeks", not "Egyptian Geeks", which is wrong.

EgyGeeks is another group and podcast (started long before Egyptian Geeks), that, although being on hold, and all it's members are proud admins of Egyptian Geeks, is not the same page and is not meant to be merged).

EgyGeeks URL:
https://www.facebook.com/pages/EgyGeeks/117311724947028

Egyptian Geeks URL:
https://www.facebook.com/groups/egyptian.geeks/

**Comment by MohamedAlaa** [comment]
Thanks a lot Mohamed for Adding this important note. The Admins of EgyGeeks will make an announcement in the Group talking about Merging with Egyptian Geeks.

This doesn't have to do anything with which Group is better or which group was founded before the other however We both share the same objective, mission and even admins that's how the idea of the merge came out and it was actually being proposed by EgyGeeks.

I personally received several PMs mentioning the same exact point of view you have and That's why the EgyGeeks Admins will make their statement today.

Thanks,
Mohamed

**Comment by Meligy** [comment]
You are talking to one of the founders and admins of EgyGeeks.

@AmrEldib talked to me and another admin Emad Mokhtar and stated that he will correct this mistake soon (this was short before Suhor time and he said the change in Github will take time).

There is no merging agreed by the admins. I'm very surprised you are speaking on our behalf actually!

This is simply an honest mistake by one of EgyGeeks admins and he promised it'll be corrected.

**Comment by MohamedAlaa** [comment]
Yes, I got the update yesterday as well. we will see the owner of the Repo and fix the naming and i believe Amr already removed the logos.

**Comment by emad-elsaid** [comment]
changing name and image could be done from this link 
https://github.com/organizations/egygeeks/settings/profile
i didn't do it as i don't know exactly what should i change and if i should do it.

**Comment by Meligy** [comment]
Wouldn't just replacing EgyGeeks with EgyyptianGeeks do the trick?

**Comment by emad-elsaid** [comment]
i'll do it now.

**Comment by emad-elsaid** [comment]
i renamed the group, looking for a suitable logo to replace the current one.

**Comment by Meligy** [comment]
Leave the logo for @MohamedAlaa - he has the talent, skill, and probably tools to sort it out. Just moving the user/org and repo into new name and maybe including same admins in the repos will be all enough.

Thank you BTW

**Comment by emad-elsaid** [comment]
what i did now is : 
1- renamed group to EgyptianGeeks
2- replaed logo with an Egyptian half setting man as a temporary logo.
if anything else is needed please let me know, or else please close the issue when you feel suitable.

**Comment by Meligy** [comment]
I think the github user or organization and repo names need to change

**Comment by emad-elsaid** [comment]
i noticed the url was still 'egygeek' despite me changing the name, but github had another extra step to rename the url separately. i did it and egyptiangeeks was taken, so i renamed the url to egyptian-geeks.
did that correct the issue ?

**Comment by mtayseer** [comment]
I renamed the repo as well. I created the group with the name "egygeeks". I
didn't remember the other group.

On Tue, Jul 22, 2014 at 4:19 PM, Emad Elsaid notifications@github.com
wrote:

> i noticed the url was still 'egypgeek' despite me changing the name, but
> github had another extra step to rename the url separately. i did it and
> egyptiangeeks was taken, so i renamed the url to egyptian-geeks.
> did that correct the issue ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/egyptian-geeks/EgyptianGeeksArchive/issues/14#issuecomment-49744932
> .

## 

_Mohammad Tayseer_
My site: http://mtayseer.net
My projects: http://mtayseer.net/projects/, https://github.com/mtayseer
Twitter: http://twitter.com/m_tayseer

**Comment by Meligy** [comment]
For this issue yes. I don't know who owns the user/organization. @MohamedAlaa might own it, or @AmrEldib. I don't know. As for this issue, it's complete.

P.S.

Github still redirects the https://github.com/egygeeks/EgyGeeksArchive to the new URL. That's why my window still worked with old name even after change and I didn't see it. It's funny because the URL 
https://github.com/egygeeks doesn't redirect! But that's fine though.

**Comment by emad-elsaid** [comment]
great, i'll be glade to help anytime, i'm one of this org owners, Mr.@mtayseer listed me as one, so let me know if you need any other mods, and we are sorry for this copyright violation.

**Comment by MohamedAlaa** [comment]
Thanks a lot Emad for Fixing thins mis-understanding. Yes today I will be working on a new logo, new cover image and new planning for the Hangouts :)
