### ISSUE TITLE
Convert post text to HTML

### ISSUE THREAD

**Issue by mtayseer** [egyptian-geeks/EgyptianGeeksArchive#19]
This is an example of a post which needs fixing. Mostly convert new lines to <br>
http://egyptian-geeks.github.io/EgyptianGeeksArchive/post.html?id=172338516139198_786736254699418

**Comment by AmrEldib** [comment]
In the CreateSummary.js file, line 45 is commented (my mistake).
Uncommenting this line should add the line breaks.
However, @kashwaa just added Generating Summary to the .NET application
https://github.com/egyptian-geeks/fb_group_archiver/pull/2
So, I think we'll have to fix it there.
