### ISSUE TITLE
Update README :: How to Install and run the app

### ISSUE THREAD

**Issue by ahmadajmi** [egyptian-geeks/EgyptianGeeksArchive#22]
We need to add simple steps for running the app, I opened the index.html and nothing happens. It looks like ASP.net config files is used which I have no idea about.

Thanks

**Comment by AmrEldib** [comment]
It's meant to be used as a website. Use this [link](http://egyptian-geeks.github.io/EgyptianGeeksArchive) to visit it.
If you'd like to set it up on your machine, set it up as an IIS application.

**Comment by ahmadajmi** [comment]
Yes I want to run it on my machine, but I don't know how is it easy to run it on Mac.
I think it would be great if we can manage it so everyone can clone and run it easily on whatever OS he use.

**Comment by AmrEldib** [comment]
Good idea. For now, you can use the hosted version.
If you figure out how to set it up on a Mac, feel free to add those instructions to the README file.

**Comment by mtayseer** [comment]
`python -m SimpleHTTPServer` _should_ work on Linux & Mac (& Windows also if you have Python installed), but it didn't work when I tried it. I'm working on it now.

**Comment by mtayseer** [comment]
Fixed [here](https://github.com/egyptian-geeks/EgyptianGeeksArchive/commit/4653d4eebf8f6b2142b3c7e1b0aff4a15f2f3c5e)

**Comment by AhmedKamal** [comment]
It only shows the top bar but the posts don't appear.

I tried to open it using VS through Open Websites

**Comment by ahmadajmi** [comment]
Perfect! It works with `python -m SimpleHTTPServer`
Thanks
