### ISSUE TITLE
Did we consider static site generators?

### ISSUE THREAD

**Issue by emad-elsaid** [egyptian-geeks/EgyptianGeeksArchive#24]
there are some good static site generators out there for example octopress and jekyll 
these generators uses plain markdown files and translate them into blog posts through themes, and they have lots or themes to choose of.
so did we consider using these generators instead of creating our own solution ? 
also they are fully compatible with github-pages.
http://octopress.org/
http://jekyllrb.com/
http://jekyllthemes.org/
https://github.com/imathis/octopress/wiki/3rd-Party-Octopress-Themes

**Comment by mtayseer** [comment]
Fork the repo & show us.

On Thu, Jul 24, 2014 at 12:07 PM, Emad Elsaid notifications@github.com
wrote:

> there are some good static site generators out there for example octopress
> and jekyll
> these generators uses plain markdown files and translate them into blog
> posts through themes, and they have lots or themes to choose of.
> so did we consider using these generators instead of creating our own
> solution ?
> also they are fully compatible with github-pages.
> http://octopress.org/
> http://jekyllrb.com/
> http://jekyllthemes.org/
> https://github.com/imathis/octopress/wiki/3rd-Party-Octopress-Themes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/egyptian-geeks/EgyptianGeeksArchive/issues/24.

## 

_Mohammad Tayseer_
My site: http://mtayseer.net
My projects: http://mtayseer.net/projects/, https://github.com/mtayseer
Twitter: http://twitter.com/m_tayseer

**Comment by emad-elsaid** [comment]
ok, i'll try to create a group exporter into markdown and jekyll theme looks like facebook.

**Comment by AmrEldib** [comment]
It seems Jekyll supports JSON as an input format
"Jekyll supports loading data from YAML and JSON files located in the _data directory."
http://jekyllrb.com/docs/datafiles/

**Comment by kashwaa** [comment]
I could alter the c# application to export posts to any format that you choose
@blazeeboy give me a sample of the required format and I'll do it for you

**Comment by ahmedelgabri** [comment]
There are more than just Jekyll & Octopress.

You can check theme here:
- https://www.staticgen.com/
- http://staticsitegenerators.net/
